In [1]:
import numpy as np

In [2]:
np.__version__

'1.18.1'

In [7]:
arr1 = np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
arr2 = np.arange(3).reshape(3,1)
arr2

array([[0],
       [1],
       [2]])

In [9]:
arr2.ndim

1

In [11]:
arr1 + arr2

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [13]:
arr2 = arr2.flatten()
arr2

array([0, 1, 2])

In [17]:
arr1.ravel() #Wypłaszczanie tablicy

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [18]:
arr1 + arr2

array([[ 0,  2,  4],
       [ 3,  5,  7],
       [ 6,  8, 10]])

In [19]:
arr1 * 2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

### Tablica wygenerowana w sposob losowy

In [4]:
arr = 1

NameError: name 'np' is not defined

In [7]:
for i in range (arr.ahape[0]):
    print("="*50)
    print(arr[i])

NameError: name 'arr' is not defined

In [11]:
lista = range(1000)
%timeit -r 5 -n 1000 [i**2 for i in lista]


203 µs ± 8.08 µs per loop (mean ± std. dev. of 5 runs, 1000 loops each)


In [12]:
arr = np.arange(1000)
%timeit -r 5 -n 1000 arr**2 

NameError: name 'np' is not defined